# Generated by Django 5.2.14 on 2026-05-28 11:24

import common.orm
import local.api_app.models.orm
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Finding',
            fields=[
                ('id', models.CharField(default=common.orm.new_uuid_hex, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('scan_id', models.CharField(db_index=True, max_length=32)),
                ('created_by', models.CharField(blank=True, default='', max_length=32)),
                ('cwe', models.CharField(blank=True, default='', max_length=255)),
                ('cvss_vector', models.CharField(blank=True, default='', max_length=255)),
                ('cvss_score', models.CharField(blank=True, default='', max_length=32)),
                ('code', models.CharField(blank=True, default='', max_length=64)),
                ('title', models.TextField(blank=True, default='')),
                ('description', models.TextField(blank=True, default='')),
                ('severity', models.CharField(blank=True, default='', max_length=32)),
                ('file_path', models.CharField(blank=True, default='', max_length=512)),
                ('code_snip', models.TextField(blank=True, default='')),
                ('security_risk', models.TextField(blank=True, default='')),
                ('mitigation', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='open', max_length=32)),
                ('deleted', models.BooleanField(default=False)),
                ('approved', models.BooleanField(default=False)),
                ('reference', models.CharField(blank=True, default='', max_length=512)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'findings',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.CharField(default=common.orm.new_uuid_hex, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('preset', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('created_by', models.CharField(blank=True, default='', max_length=32)),
                ('created_at', models.DateTimeField()),
                ('deleted', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='SbomFinding',
            fields=[
                ('id', models.CharField(default=common.orm.new_uuid_hex, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('scan_id', models.CharField(db_index=True, max_length=32)),
                ('package_name', models.CharField(blank=True, default='', max_length=255)),
                ('package_version', models.CharField(blank=True, default='', max_length=128)),
                ('package_type', models.CharField(blank=True, default='', max_length=64)),
                ('cve_id', models.CharField(blank=True, default='', max_length=64)),
                ('severity', models.CharField(blank=True, default='', max_length=32)),
                ('description', models.TextField(blank=True, default='')),
                ('cvss', models.JSONField(default=list)),
                ('fix_versions', models.JSONField(default=list)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'sbom_findings',
            },
        ),
        migrations.CreateModel(
            name='SbomLicenseFinding',
            fields=[
                ('id', models.CharField(default=common.orm.new_uuid_hex, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('scan_id', models.CharField(db_index=True, max_length=32)),
                ('package_name', models.CharField(blank=True, default='', max_length=255)),
                ('package_version', models.CharField(blank=True, default='', max_length=128)),
                ('package_type', models.CharField(blank=True, default='', max_length=64)),
                ('license', models.JSONField(default=dict)),
                ('decision', models.CharField(blank=True, default='', max_length=64)),
                ('locations', models.JSONField(default=list)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'sbom_licenses_findings',
            },
        ),
        migrations.CreateModel(
            name='SbomScan',
            fields=[
                ('id', models.CharField(default=common.orm.new_uuid_hex, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('project_id', models.CharField(db_index=True, max_length=32)),
                ('scan_name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(default='queued', max_length=32)),
                ('created_at', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('triggered_by', models.CharField(blank=True, default='', max_length=32)),
                ('dependencies_scanned', models.IntegerField(default=0)),
                ('vulnerabilities', models.IntegerField(default=0)),
                ('severity_counts', models.JSONField(default=local.api_app.models.orm._severity_counts_default)),
                ('ecosystems', models.JSONField(default=list)),
                ('sbom_format', models.CharField(default='syft-json', max_length=32)),
                ('deleted', models.BooleanField(default=False)),
                ('sbom_signing', models.JSONField(default=dict)),
                ('sbom_artifact', models.CharField(blank=True, default='', max_length=512)),
                ('license_policy', models.JSONField(default=dict)),
            ],
            options={
                'db_table': 'sbom_scans',
            },
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.CharField(default=common.orm.new_uuid_hex, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('project_id', models.CharField(db_index=True, max_length=32)),
                ('scan_name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(default='queued', max_length=32)),
                ('source', models.CharField(default='zip', max_length=32)),
                ('created_at', models.DateTimeField()),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('triggered_by', models.CharField(blank=True, default='', max_length=32)),
                ('total_files', models.IntegerField(default=0)),
                ('files_scanned', models.IntegerField(default=0)),
                ('findings', models.IntegerField(default=0)),
                ('error', models.TextField(blank=True, default='')),
                ('deleted', models.BooleanField(default=False)),
                ('metrics', models.JSONField(default=local.api_app.models.orm._scan_metrics_default)),
            ],
            options={
                'db_table': 'scans',
            },
        ),
    ]
