# Generated by Django 5.2.15 on 2026-06-15 05:04

import common.orm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrialUsage',
            fields=[
                ('id', models.CharField(default=common.orm.new_uuid_hex, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('scans_used', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'trial_usage',
            },
        ),
    ]
