# Generated by Django 5.2.15 on 2026-07-29 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0002_trialusage'),
        ('api_app', '0004_finding_code_snip_start_line'),
    ]

    operations = [
    ]
