# Generated by Django 5.2.15 on 2026-08-04 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0005_merge_20260729_1528'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='fingerprint',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='scan',
            name='cancel_requested',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='scan',
            name='source_path',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
