# Generated by Django 5.2.15 on 2026-08-11 16:13

import common.orm
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0007_split_trial_usage_by_scan_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('id', models.CharField(default=common.orm.new_uuid_hex, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('project_id', models.CharField(db_index=True, max_length=32)),
                ('name', models.CharField(max_length=255)),
                ('key_hash', models.CharField(max_length=64, unique=True)),
                ('key_prefix', models.CharField(max_length=16)),
                ('created_by', models.CharField(blank=True, default='', max_length=32)),
                ('created_at', models.DateTimeField()),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'api_keys',
            },
        ),
    ]
