# Generated by Django 5.2.15 on 2026-08-12 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0008_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='scan',
            name='file_manifest',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='scan',
            name='ruleset_version',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
