# Generated by Django 5.2.15 on 2026-08-12 00:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_app', '0009_scan_file_manifest_scan_ruleset_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='finding',
            name='first_seen_scan_id',
            field=models.CharField(blank=True, db_index=True, default='', max_length=32),
        ),
    ]
