"""
Django settings for codesense project.

Generated by 'django-admin startproject' using Django 5.2.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Per-user writable data directory (overridable by the desktop launcher).
DATA_DIR = Path(os.getenv("CODESENSE_DATA_DIR", BASE_DIR / "data"))
DATA_DIR.mkdir(parents=True, exist_ok=True)

# Off by default for the packaged app; opt in with DJANGO_DEBUG=true in dev.
DEBUG = os.getenv("DJANGO_DEBUG", "False").lower() == "true"


def _load_or_create_secret_key() -> str:
    """Use DJANGO_SECRET_KEY if set, else a per-install key persisted in DATA_DIR."""
    env_key = os.getenv("DJANGO_SECRET_KEY")
    if env_key:
        return env_key
    key_file = DATA_DIR / "secret_key"
    if key_file.exists():
        return key_file.read_text(encoding="utf-8").strip()
    from django.core.management.utils import get_random_secret_key
    key = get_random_secret_key()
    key_file.write_text(key, encoding="utf-8")
    return key


SECRET_KEY = _load_or_create_secret_key()

ALLOWED_HOSTS = os.getenv("DJANGO_ALLOWED_HOSTS", "127.0.0.1,localhost").split(",")

# Cloud hosts (e.g. Railway) serve over HTTPS on a generated domain; Django needs the
# scheme-qualified origin trusted for admin/CSRF-protected POSTs. Comma-separated env.
CSRF_TRUSTED_ORIGINS = [o for o in os.getenv("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",") if o]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',  # needed for the Browsable API templates/static (HTML renderer)
    'local.auth_app',
    'local.api_app',
    'scanner',
    'corsheaders',
    'licenses'
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',  # <-- must be first!
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # serves static files with DEBUG off
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'licenses.middleware.ActivationRequiredMiddleware',
    'licenses.middleware.ReadOnlyGraceMiddleware',
]

ROOT_URLCONF = 'codesense.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'codesense.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": str(DATA_DIR / "app.sqlite3"),
        # Real file (not Django's default ":memory:") so tests can open a second,
        # independent sqlite3 connection to the same DB -- needed to exercise
        # cross-connection commit visibility (see
        # local/api_app/tests/test_background_thread_db_cleanup.py).
        "TEST": {"NAME": str(DATA_DIR / "test_app.sqlite3")},
    }
}

# Loopback desktop app: the Tauri webview origin is tauri://localhost (on Windows
# http(s)://tauri.localhost). Allow those + the dev server; allow-all only in DEBUG.
CORS_ALLOW_ALL_ORIGINS = DEBUG
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    "tauri://localhost",         # macOS / Linux webview origin (custom scheme)
    "http://tauri.localhost",    # Windows webview origin
    "https://tauri.localhost",
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:8585",
    "http://127.0.0.1:8585",
]
# Belt-and-suspenders: match the custom tauri:// scheme by regex too, since some
# django-cors-headers versions only exact-match http(s) entries in the list above.
CORS_ALLOWED_ORIGIN_REGEXES = [r"^tauri://localhost$"]

# Extra browser origins for a hosted web frontend (comma-separated), e.g. the
# Railway frontend URL. Added on top of the desktop/localhost origins above.
CORS_ALLOWED_ORIGINS += [o for o in os.getenv("DJANGO_CORS_ALLOWED_ORIGINS", "").split(",") if o]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        # Your JWT middleware sets request.user — no DRF auth class needed
        # If you want DRF-style permissions (`IsAuthenticated`), you can use a custom JWTAuthentication class later
        # 'local.auth_app.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        # 'rest_framework.permissions.AllowAny',
        # 'rest_framework.permissions.IsAuthenticated',
    ]
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / "staticfiles"
# WhiteNoise: compress + serve static directly from the app process (no separate CDN).
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {"BACKEND": "whitenoise.storage.CompressedStaticFilesStorage"},
}

CENTRAL_URL = os.getenv("CENTRAL_URL")
LOCAL_KEYS_DIR = os.getenv("LOCAL_KEYS_DIR")

# Offline license (Phase 4): self-contained, runs N days from first launch.
LICENSE_DURATION_DAYS = int(os.getenv("LICENSE_DURATION_DAYS", "90"))
LICENSE_SECRET = os.getenv("LICENSE_SECRET")  # build-injected; dev falls back to a constant

# One-time activation gate (Phase: client-delivery hardening). A bcrypt hash of
# the activation password, build-injected via main.rs -- unset in dev/from-
# source runs, which leaves the gate fully disabled (see licenses/services/
# activation.py::is_configured()).
ACTIVATION_PASSWORD_HASH = os.getenv("ACTIVATION_PASSWORD_HASH")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
