# Generated by Django 5.2.14 on 2026-05-28 11:16

import common.orm
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50, unique=True)),
                ('permissions', models.JSONField(default=dict)),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'permissions',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(default=common.orm.new_uuid_hex, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('email', models.CharField(db_index=True, max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(default='User', max_length=50)),
                ('deleted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
